# Test Set Creation

In [1]:
import gzip
import json
import os
import warnings
import requests
import urllib.request
from glob import glob

# import get_pdb_data
import pandas as pd
from Bio.PDB import PDBParser
from tqdm import tqdm
from SPARQLWrapper import SPARQLWrapper, JSON
import itertools

def uniref50_clusters(uniprot_ids):
    # Set the SPARQL endpoint (UniProt)
    sparql = SPARQLWrapper("https://sparql.uniprot.org/sparql")

    output = []
    for uniprot_subset in tqdm(itertools.batched(uniprot_ids, 200)):
        uniprot_string = ' '.join([f'uniprotkb:{id}' for id in uniprot_subset])
                 
        # Define the query
        query_string = f"""
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX uniprotkb: <http://purl.uniprot.org/uniprot/>
PREFIX uniref: <http://purl.uniprot.org/uniref/>

SELECT ?primaryAccession ?cluster_id
FROM <http://sparql.uniprot.org/uniref>
FROM <http://sparql.uniprot.org/uniprot>
WHERE
{{
    VALUES ?protein {{ {uniprot_string} }}
    ?cluster up:member/up:sequenceFor ?protein;
             up:identity 0.5 .
    BIND(substr(str(?protein), strlen(str(uniprotkb:))+1) AS ?primaryAccession)
    BIND(substr(str(?cluster), strlen(str(uniref:))+1) AS ?cluster_id)
}}"""
        sparql.setQuery(query_string)
    
        # Set the output format as JSON
        sparql.setReturnFormat(JSON)
        
        # Run the SPARQL query and convert to the defined format
        results = sparql.query().convert()

        # Print the query result
        for result in results["results"]["bindings"]:
            output.append([result["primaryAccession"]["value"],
                           result["cluster_id"]["value"]])
    return pd.DataFrame(output, columns=['uniprot_id', 'uniref50_cluster'])


protein_letters_1to3 = {"A": "ALA", "C": "CYS", "D": "ASP", "E": "GLU",
                        "F": "PHE", "G": "GLY", "H": "HIS", "I": "ILE",
                        "K": "LYS", "L": "LEU", "M": "MET", "N": "ASN",
                        "P": "PRO", "Q": "GLN", "R": "ARG", "S": "SER",
                        "T": "THR", "V": "VAL", "W": "TRP", "Y": "TYR"}

Combined of list of PDBs used to train AlloPred, AlloSite, PASSER, and other ML based allosteric site prediction packages

In [2]:
df_training = pd.read_csv('../output/proteins_in_training_sets.csv')

In [3]:
print('Number of Rows:             ', df_training.shape[0])
print('Number of Unique PDB IDs:   ', df_training['pdb_id'].nunique())
print('Number of Unique UniProt AC:', df_training['uniprot_id'].nunique())

Number of Rows:              366
Number of Unique PDB IDs:    360
Number of Unique UniProt AC: 266

In [4]:
df_asd_with_active_site = pd.read_csv('../output/ASD_Release_202306.csv')

In [5]:
def get_chain(residues):
    return {res.split('-')[0] for res in residues}

df_asd_with_active_site['allosteric_site_chains'] = df_asd_with_active_site['allosteric_site_residue'].apply(eval).apply(get_chain)

df_asd_with_active_site[['pdb_uniprot', 'allosteric_pdb', 'allosteric_site_residue', 'modulator_chain', 'allosteric_site_chains']]

,pdb_uniprot,allosteric_pdb,allosteric_site_residue,modulator_chain,allosteric_site_chains
0,P0AB91,1KFL,"['A-PRO-150', 'A-GLN-151', 'A-ALA-154', 'A-GLY...",A,"{B, A}"
1,P00888,6AGM,[],A,{}
2,Q9WYH8,3PG9,"['A-SER-31', 'A-GLY-33', 'A-GLN-34', 'A-GLU-35...",A,"{F, A}"
3,P32449,1OF6,"['A-THR-162', 'A-GLN-166', 'A-ALA-169', 'A-GLY...",A,"{B, A}"
4,P32449,1OFR,"['G-THR-162', 'G-PRO-165', 'G-GLN-166', 'G-ALA...",H,"{G, H}"
...,...,...,...,...,...
3167,NaN,3OWW,['A-GLY-36'],A,{A}
3168,NaN,3IRW,['R-ALA-47'],R,{R}
3169,NaN,3MXH,['R-ALA-47'],R,{R}
3170,NaN,3OXE,['A-GLY-36'],A,{A}
3171,NaN,3MUM,['R-ALA-47'],R,{R}

In [6]:
print('Number of Rows:             ', df_asd_with_active_site.shape[0])
print('Number of Unique PDB IDs:   ', df_asd_with_active_site['allosteric_pdb'].nunique())
print('Number of Unique UniProt AC:', df_asd_with_active_site['pdb_uniprot'].nunique())

Number of Rows:              3172
Number of Unique PDB IDs:    2991
Number of Unique UniProt AC: 700

## Get UniRef Clusters

In [7]:
df_training_clusters = uniref50_clusters(df_training['uniprot_id'].drop_duplicates())

0it [00:00, ?it/s]

PREFIX up: <http://purl.uniprot.org/core/>
PREFIX uniprotkb: <http://purl.uniprot.org/uniprot/>
PREFIX uniref: <http://purl.uniprot.org/uniref/>

SELECT ?primaryAccession ?cluster_id
FROM <http://sparql.uniprot.org/uniref>
FROM <http://sparql.uniprot.org/uniprot>
WHERE
{
    VALUES ?protein { uniprotkb:P00669 uniprotkb:P00497 uniprotkb:P68871 uniprotkb:P34896 uniprotkb:P00968 uniprotkb:P27623 uniprotkb:P32178 uniprotkb:P19367 uniprotkb:P11473 uniprotkb:P29477 uniprotkb:P14193 uniprotkb:P03023 uniprotkb:Q00441 uniprotkb:P06737 uniprotkb:P0A6I3 uniprotkb:P58301 uniprotkb:P62942 uniprotkb:P0A1E3 uniprotkb:P00864 uniprotkb:P0A759 uniprotkb:P09467 uniprotkb:Q99279 uniprotkb:Q9HU22 uniprotkb:P69905 uniprotkb:P00489 uniprotkb:P23368 uniprotkb:P37744 uniprotkb:P07071 uniprotkb:P0A8V6 uniprotkb:P08758 uniprotkb:P00898 uniprotkb:P00953 uniprotkb:P00897 uniprotkb:P03366 uniprotkb:Q26998 uniprotkb:P00929 uniprotkb:P0A6F5 uniprotkb:P00636 uniprotkb:P00344 uniprotkb:E8ME30 uniprotkb:Q12650 uniprotkb:Q922S4 uniprotkb:P17707 uniprotkb:P9WMN1 uniprotkb:Q9TZZ6 uniprotkb:P27443 uniprotkb:P32449 uniprotkb:Q08698 uniprotkb:P0A796 uniprotkb:P0ACP7 uniprotkb:P04058 uniprotkb:P0A434 uniprotkb:O85142 uniprotkb:P20701 uniprotkb:P0ABQ4 uniprotkb:Q02750 uniprotkb:P00734 uniprotkb:P55210 uniprotkb:P18910 uniprotkb:P18031 uniprotkb:P14618 uniprotkb:O76074 uniprotkb:P0A7F3 uniprotkb:O25926 uniprotkb:O57693 uniprotkb:P35557 uniprotkb:P10943 uniprotkb:P0AD64 uniprotkb:Q980Q4 uniprotkb:P08684 uniprotkb:B8GZM2 uniprotkb:Q00955 uniprotkb:P52732 uniprotkb:O33839 uniprotkb:O35627 uniprotkb:P19793 uniprotkb:Q9WUI9 uniprotkb:P0A7G6 uniprotkb:P0A6D0 uniprotkb:P08709 uniprotkb:P0A6L2 uniprotkb:P77425 uniprotkb:P11217 uniprotkb:P38501 uniprotkb:P0ACJ8 uniprotkb:Q8RQE9 uniprotkb:P19491 uniprotkb:Q9WZ31 uniprotkb:P74766 uniprotkb:P0A7E9 uniprotkb:Q9X2A4 uniprotkb:Q15119 uniprotkb:P02768 uniprotkb:Q59643 uniprotkb:Q9S7B5 uniprotkb:Q9LYU8 uniprotkb:P02062 uniprotkb:Q9UM07 uniprotkb:O57883 uniprotkb:P06709 uniprotkb:Q92731 uniprotkb:P00533 uniprotkb:P60891 uniprotkb:P21836 uniprotkb:P0A962 uniprotkb:Q8DSE5 uniprotkb:Q8TE04 uniprotkb:Q9H999 uniprotkb:Q5HEB7 uniprotkb:P49902 uniprotkb:P22634 uniprotkb:Q9ZLT0 uniprotkb:P08799 uniprotkb:P43246 uniprotkb:A0A0H2UNK6 uniprotkb:P04818 uniprotkb:P0A9T0 uniprotkb:P10275 uniprotkb:P53704 uniprotkb:P51852 uniprotkb:P0A993 uniprotkb:O67854 uniprotkb:Q2K340 uniprotkb:Q8KBW6 uniprotkb:P00452 uniprotkb:Q9SCL7 uniprotkb:A0A0H3ADR8 uniprotkb:P80385 uniprotkb:O27550 uniprotkb:P43889 uniprotkb:P30613 uniprotkb:Q12629 uniprotkb:P51561 uniprotkb:Q836J0 uniprotkb:A0R3E2 uniprotkb:A0R2B1 uniprotkb:P69834 uniprotkb:Q9Y233 uniprotkb:Q72498 uniprotkb:O57946 uniprotkb:Q58718 uniprotkb:A0A348ACF3 uniprotkb:P39669 uniprotkb:P22756 uniprotkb:P06999 uniprotkb:P32589 uniprotkb:Q5FAK7 uniprotkb:P52731 uniprotkb:P9WNX3 uniprotkb:P45148 uniprotkb:B8FW11 uniprotkb:Q9KS12 uniprotkb:Q8X607 uniprotkb:P00366 uniprotkb:P0CW58 uniprotkb:O88703 uniprotkb:Q99814 uniprotkb:P00523 uniprotkb:Q8F3Q1 uniprotkb:O14757 uniprotkb:P9WQB3 uniprotkb:P09960 uniprotkb:P26663 uniprotkb:Q16539 uniprotkb:P42684 uniprotkb:P68400 uniprotkb:P04995 uniprotkb:P23921 uniprotkb:P16154 uniprotkb:A0A0H3JRU9 uniprotkb:Q9HUK6 uniprotkb:P04585 uniprotkb:Q08499 uniprotkb:P05132 uniprotkb:P12369 uniprotkb:O00757 uniprotkb:P14174 uniprotkb:Q836G9 uniprotkb:P37231 uniprotkb:P01008 uniprotkb:P12499 uniprotkb:O53512 uniprotkb:Q58622 uniprotkb:P42574 uniprotkb:P74569 uniprotkb:P0A4U6 uniprotkb:P9WPY9 uniprotkb:P19492 uniprotkb:P08069 uniprotkb:P07834 uniprotkb:A1R118 uniprotkb:P9WMH3 uniprotkb:P14324 uniprotkb:O15530 uniprotkb:P12497 uniprotkb:P88911 uniprotkb:P45983 uniprotkb:P31749 uniprotkb:P07278 uniprotkb:P03372 }
    ?cluster up:member/up:sequenceFor ?protein;
             up:identity 0.5 .
    BIND(substr(str(?protein), strlen(str(uniprotkb:))+1) AS ?primaryAccession)
    BIND(substr(str(?cluster), strlen(str(uniref:))+1) AS ?cluster_id)
}

1it [00:03,  3.38s/it]

PREFIX up: <http://purl.uniprot.org/core/>
PREFIX uniprotkb: <http://purl.uniprot.org/uniprot/>
PREFIX uniref: <http://purl.uniprot.org/uniref/>

SELECT ?primaryAccession ?cluster_id
FROM <http://sparql.uniprot.org/uniref>
FROM <http://sparql.uniprot.org/uniprot>
WHERE
{
    VALUES ?protein { uniprotkb:Q189K3 uniprotkb:P42527 uniprotkb:Q9WYH8 uniprotkb:A0A0J9WZA6 uniprotkb:P00735 uniprotkb:P00514 uniprotkb:O60701 uniprotkb:P24941 uniprotkb:P00519 uniprotkb:P29274 uniprotkb:Q00960 uniprotkb:Q05769 uniprotkb:P49427 uniprotkb:P21524 uniprotkb:O60678 uniprotkb:Q9X1X1 uniprotkb:P35559 uniprotkb:O94925 uniprotkb:A0A0H3JPA5 uniprotkb:P37975 uniprotkb:P35790 uniprotkb:P27338 uniprotkb:P56106 uniprotkb:P05121 uniprotkb:O05581 uniprotkb:P0A6Y8 uniprotkb:O54438 uniprotkb:Q386Q8 uniprotkb:P30694 uniprotkb:Q9Y3Z3 uniprotkb:Q9NTG7 uniprotkb:P53608 uniprotkb:P54646 uniprotkb:Q05397 uniprotkb:Q9HZE7 uniprotkb:P15056 uniprotkb:P42676 uniprotkb:P04746 uniprotkb:D7U7T8 uniprotkb:Q9UDY8 uniprotkb:P02766 uniprotkb:P0DMV8 uniprotkb:P48735 uniprotkb:P0ABH7 uniprotkb:Q0ASS9 uniprotkb:P01116 uniprotkb:Q08881 uniprotkb:A4INJ9 uniprotkb:P51681 uniprotkb:P55212 uniprotkb:Q81VW8 uniprotkb:Q9WMX2 uniprotkb:Q5ZZB6 uniprotkb:P41594 uniprotkb:I6YFP0 uniprotkb:P0ABE7 uniprotkb:Q96PN6 uniprotkb:Q2HRB6 uniprotkb:H6WFU3 uniprotkb:Q9PTN2 uniprotkb:Q8DRB3 uniprotkb:P51668 uniprotkb:nan uniprotkb:P53671 uniprotkb:P06730 uniprotkb:Q90EA1 uniprotkb:P35520 }
    ?cluster up:member/up:sequenceFor ?protein;
             up:identity 0.5 .
    BIND(substr(str(?protein), strlen(str(uniprotkb:))+1) AS ?primaryAccession)
    BIND(substr(str(?cluster), strlen(str(uniref:))+1) AS ?cluster_id)
}

2it [00:04,  2.05s/it]

In [8]:
df_traning_merged = df_training.merge(df_training_clusters, how='left')
df_traning_merged

,pdb_id,uniprot_id,asd90,allosite,passer_ensemble,allositepro,allopred,passer_automl,passer_rank,uniref50_cluster
0,11BG,P00669,NaN,NaN,NaN,True,True,True,True,UniRef50_P07998
1,1AO0,P00497,True,True,True,NaN,NaN,NaN,NaN,UniRef50_P00497
2,1B86,P68871,NaN,NaN,NaN,True,True,NaN,NaN,UniRef50_P68871
3,1BJ4,P34896,NaN,NaN,NaN,NaN,NaN,True,True,UniRef50_P34896
4,1CE8,P00968,True,True,True,True,True,True,True,UniRef50_P00968
...,...,...,...,...,...,...,...,...,...,...
361,4TPT,P53671,NaN,NaN,NaN,NaN,NaN,True,True,UniRef50_P53671
362,4TQC,P06730,NaN,NaN,NaN,NaN,NaN,True,True,UniRef50_P06730
363,4TVG,Q90EA1,NaN,NaN,NaN,NaN,NaN,True,True,UniRef50_P04585
364,4UUU,P35520,NaN,NaN,NaN,NaN,NaN,True,True,UniRef50_P35520
365,6DHM,P00366,NaN,NaN,NaN,True,NaN,NaN,NaN,UniRef50_P00367

In [9]:
df_asd_clusters = uniref50_clusters(df_asd_with_active_site['pdb_uniprot'].drop_duplicates())
df_asd_merged = df_asd_with_active_site.merge(df_asd_clusters, how='left', left_on='pdb_uniprot', right_on='uniprot_id')

0it [00:00, ?it/s]

PREFIX up: <http://purl.uniprot.org/core/>
PREFIX uniprotkb: <http://purl.uniprot.org/uniprot/>
PREFIX uniref: <http://purl.uniprot.org/uniref/>

SELECT ?primaryAccession ?cluster_id
FROM <http://sparql.uniprot.org/uniref>
FROM <http://sparql.uniprot.org/uniprot>
WHERE
{
    VALUES ?protein { uniprotkb:P0AB91 uniprotkb:P00888 uniprotkb:Q9WYH8 uniprotkb:P32449 uniprotkb:Q9K169 uniprotkb:O15530 uniprotkb:P30542 uniprotkb:P29274 uniprotkb:P21836 uniprotkb:P04058 uniprotkb:P17707 uniprotkb:P23509 uniprotkb:P39669 uniprotkb:P00497 uniprotkb:P0AG16 uniprotkb:P80385 uniprotkb:P54645 uniprotkb:Q9Y478 uniprotkb:P54619 uniprotkb:O43741 uniprotkb:Q58622 uniprotkb:P54646 uniprotkb:P00898 uniprotkb:P00897 uniprotkb:E8Y329 uniprotkb:P0A7F3 uniprotkb:P74766 uniprotkb:Q57991 uniprotkb:Q9LYU8 uniprotkb:P74569 uniprotkb:P53396 uniprotkb:Q12650 uniprotkb:Q00955 uniprotkb:P06709 uniprotkb:O57883 uniprotkb:I6YFP0 uniprotkb:P15056 uniprotkb:P41180 uniprotkb:P62158 uniprotkb:P0ACJ8 uniprotkb:P9WMH3 uniprotkb:P9WMH2 uniprotkb:I6Y496 uniprotkb:P55222 uniprotkb:P00968 uniprotkb:P68400 uniprotkb:P29466 uniprotkb:P42574 uniprotkb:P55210 uniprotkb:O14757 uniprotkb:P00268 uniprotkb:Q92731 uniprotkb:P32178 uniprotkb:P0ABH7 uniprotkb:P34998 uniprotkb:P00523 uniprotkb:P0A7E5 uniprotkb:P35520 uniprotkb:P08684 uniprotkb:Q00441 uniprotkb:P49902 uniprotkb:Q5HEB7 uniprotkb:O92972 uniprotkb:Q9HXM5 uniprotkb:Q8DSE5 uniprotkb:P0A6L2 uniprotkb:Q9I4W3 uniprotkb:Q9PPB4 uniprotkb:P52732 uniprotkb:P00533 uniprotkb:P34913 uniprotkb:P03372 uniprotkb:P13036 uniprotkb:P09467 uniprotkb:O00757 uniprotkb:P00636 uniprotkb:P0A993 uniprotkb:P14867 uniprotkb:P62812 uniprotkb:Q9UBS5 uniprotkb:O75899 uniprotkb:P43889 uniprotkb:Q386Q8 uniprotkb:P43220 uniprotkb:P35557 uniprotkb:P0A759 uniprotkb:P46926 uniprotkb:P42262 uniprotkb:P19491 uniprotkb:P00366 uniprotkb:O57693 uniprotkb:P0A6F3 uniprotkb:P11217 uniprotkb:P06737 uniprotkb:P00489 uniprotkb:P13807 uniprotkb:P0A6F5 uniprotkb:Q548M1 uniprotkb:P45148 uniprotkb:D0PY27 uniprotkb:P19367 uniprotkb:P08581 uniprotkb:P0A6Y8 uniprotkb:P08107 uniprotkb:P31645 uniprotkb:P10943 uniprotkb:P08069 uniprotkb:P12268 uniprotkb:P18910 uniprotkb:P35559 uniprotkb:Q76353 uniprotkb:P06756 uniprotkb:P20701 uniprotkb:P48735 uniprotkb:P28834 uniprotkb:P00344 uniprotkb:P03023 uniprotkb:P0A962 uniprotkb:P11229 uniprotkb:P08172 uniprotkb:P08173 uniprotkb:P08912 uniprotkb:P23368 uniprotkb:P27443 uniprotkb:P41594 uniprotkb:Q02750 uniprotkb:P29678 uniprotkb:P36507 uniprotkb:Q5FAK7 uniprotkb:Q0ASS9 uniprotkb:P35439 uniprotkb:Q12879 uniprotkb:P0A1E3 uniprotkb:P0A434 uniprotkb:Q8TE04 uniprotkb:M1VAN7 uniprotkb:P00439 uniprotkb:P51852 uniprotkb:Q08499 uniprotkb:O76074 uniprotkb:Q8CG03 uniprotkb:P00864 uniprotkb:P04711 uniprotkb:P06999 uniprotkb:P9WNX3 uniprotkb:P0A9T0 uniprotkb:P14193 uniprotkb:P60891 uniprotkb:O75469 uniprotkb:Q8KBW6 uniprotkb:A1R118 uniprotkb:P07278 uniprotkb:P05132 uniprotkb:P18031 uniprotkb:P06169 uniprotkb:Q12629 uniprotkb:Q15119 uniprotkb:P00549 uniprotkb:P14618 uniprotkb:P30613 uniprotkb:P11974 uniprotkb:Q27686 uniprotkb:P30615 uniprotkb:P0A7G6 uniprotkb:Q7X416 uniprotkb:P21457 uniprotkb:P04585 uniprotkb:P00452 uniprotkb:O33839 uniprotkb:Q08698 uniprotkb:P23921 uniprotkb:P07071 uniprotkb:P21524 uniprotkb:P02768 uniprotkb:Q9S7B5 uniprotkb:P04818 uniprotkb:P16473 uniprotkb:Q8PDA8 uniprotkb:P00929 uniprotkb:P0A2K1 uniprotkb:P00953 uniprotkb:Q9Y223 uniprotkb:Q81K32 uniprotkb:Q58899 uniprotkb:P39131 uniprotkb:Q81S73 uniprotkb:P0A7E9 uniprotkb:P59009 uniprotkb:P9WHK5 uniprotkb:P56106 uniprotkb:Q980Q4 uniprotkb:Q26998 uniprotkb:P36544 uniprotkb:P07550 uniprotkb:P62593 uniprotkb:P0ABE7 uniprotkb:O14965 uniprotkb:P09917 uniprotkb:P31749 uniprotkb:P00669 }
    ?cluster up:member/up:sequenceFor ?protein;
             up:identity 0.5 .
    BIND(substr(str(?protein), strlen(str(uniprotkb:))+1) AS ?primaryAccession)
    BIND(substr(str(?cluster), strlen(str(uniref:))+1) AS ?cluster_id)
}

1it [00:02,  2.05s/it]

PREFIX up: <http://purl.uniprot.org/core/>
PREFIX uniprotkb: <http://purl.uniprot.org/uniprot/>
PREFIX uniref: <http://purl.uniprot.org/uniref/>

SELECT ?primaryAccession ?cluster_id
FROM <http://sparql.uniprot.org/uniref>
FROM <http://sparql.uniprot.org/uniprot>
WHERE
{
    VALUES ?protein { uniprotkb:P00519 uniprotkb:P00520 uniprotkb:P21554 uniprotkb:P0AEE3 uniprotkb:P42861 uniprotkb:O88703 uniprotkb:O76977 uniprotkb:Q9ZLT0 uniprotkb:P22634 uniprotkb:Q8Y7N7 uniprotkb:Q836J0 uniprotkb:P12497 uniprotkb:Q16539 uniprotkb:P0A796 uniprotkb:P00512 uniprotkb:P0ACP7 uniprotkb:P0A7Z4 uniprotkb:Q8RQE9 uniprotkb:P35968 uniprotkb:Q9KS12 uniprotkb:Q9PTN2 uniprotkb:P26663 uniprotkb:Q99AU2 uniprotkb:Q6B856 uniprotkb:P00735 uniprotkb:P69905 uniprotkb:P68871 uniprotkb:P01958 uniprotkb:P02062 uniprotkb:P0A6H1 uniprotkb:O25926 uniprotkb:P69834 uniprotkb:A0R2B1 uniprotkb:Q9WMX2 uniprotkb:Q01813 uniprotkb:P42684 uniprotkb:Q9X2A4 uniprotkb:Q9SCL7 uniprotkb:Q01217 uniprotkb:P31224 uniprotkb:P01008 uniprotkb:P0A6D0 uniprotkb:P9WPY8 uniprotkb:P9WPY9 uniprotkb:P17893 uniprotkb:O31408 uniprotkb:Q2G036 uniprotkb:Q05769 uniprotkb:P55212 uniprotkb:Q14790 uniprotkb:P07834 uniprotkb:Q922S4 uniprotkb:Q8F3Q1 uniprotkb:P08709 uniprotkb:P24941 uniprotkb:O85142 uniprotkb:Q59643 uniprotkb:S8F7E9 uniprotkb:P0ABQ4 uniprotkb:P45985 uniprotkb:P43235 uniprotkb:P06730 uniprotkb:P14324 uniprotkb:Q05397 uniprotkb:P47871 uniprotkb:Q9Z2W9 uniprotkb:P19492 uniprotkb:P01112 uniprotkb:P20171 uniprotkb:O36607 uniprotkb:Q72498 uniprotkb:P08660 uniprotkb:P14174 uniprotkb:P45983 uniprotkb:P08799 uniprotkb:Q96EB6 uniprotkb:Q9NTG7 uniprotkb:P38501 uniprotkb:P42336 uniprotkb:Q99UY8 uniprotkb:L8DYY9 uniprotkb:P19793 uniprotkb:Q13153 uniprotkb:Q99835 uniprotkb:P63279 uniprotkb:P04483 uniprotkb:P0ACT4 uniprotkb:P51561 uniprotkb:P00734 uniprotkb:Q189K3 uniprotkb:P61586 uniprotkb:Q93009 uniprotkb:P62837 uniprotkb:P49427 uniprotkb:O60701 uniprotkb:C4XAX5 uniprotkb:P01116 uniprotkb:P9WP49 uniprotkb:Q9H999 uniprotkb:P04995 uniprotkb:O05581 uniprotkb:B8FW11 uniprotkb:P10275 uniprotkb:P19091 uniprotkb:Q836G9 uniprotkb:P11716 uniprotkb:Q9HUK6 uniprotkb:P42527 uniprotkb:P27338 uniprotkb:P29477 uniprotkb:Q9TZZ6 uniprotkb:P31327 uniprotkb:Q9Y233 uniprotkb:Q9WZ31 uniprotkb:B8GZM2 uniprotkb:P04629 uniprotkb:Q3J125 uniprotkb:P35610 uniprotkb:O75908 uniprotkb:P22262 uniprotkb:O54438 uniprotkb:P00775 uniprotkb:P49327 uniprotkb:P9WMN1 uniprotkb:O27550 uniprotkb:O17793 uniprotkb:Q7NDN8 uniprotkb:O67854 uniprotkb:Q8X607 uniprotkb:O94925 uniprotkb:D3Z7P3 uniprotkb:P12883 uniprotkb:P32589 uniprotkb:P58301 uniprotkb:Q58718 uniprotkb:Q9X1X1 uniprotkb:P45974 uniprotkb:P14902 uniprotkb:P04746 uniprotkb:P00690 uniprotkb:P14780 uniprotkb:Q08881 uniprotkb:Q06187 uniprotkb:O73948 uniprotkb:P0CW58 uniprotkb:P37975 uniprotkb:P52731 uniprotkb:P37231 uniprotkb:Q06124 uniprotkb:Q9K492 uniprotkb:Q03405 uniprotkb:O14842 uniprotkb:Q13547 uniprotkb:Q9HZE7 uniprotkb:Q02PM6 uniprotkb:O60678 uniprotkb:O57946 uniprotkb:Q9UNQ0 uniprotkb:Q9Y3Z3 uniprotkb:P06869 uniprotkb:P10253 uniprotkb:O75460 uniprotkb:P55072 uniprotkb:O53512 uniprotkb:P43003 uniprotkb:P53779 uniprotkb:Q9HU22 uniprotkb:P37744 uniprotkb:O27819 uniprotkb:A9N7P9 uniprotkb:Q9AGY4 uniprotkb:Q7MAW7 uniprotkb:P08758 uniprotkb:P77425 uniprotkb:P53704 uniprotkb:P54132 uniprotkb:P02766 uniprotkb:P02767 uniprotkb:P09960 uniprotkb:Q99279 uniprotkb:Q74FS9 uniprotkb:P31129 uniprotkb:P41597 uniprotkb:Q13224 uniprotkb:Q00960 uniprotkb:Q9UDY8 uniprotkb:P01375 uniprotkb:G5EFZ1 uniprotkb:P02633 uniprotkb:P0A8V6 uniprotkb:Q99814 uniprotkb:P35790 uniprotkb:P15723 uniprotkb:Q8IXJ6 uniprotkb:Q9UM07 uniprotkb:P34896 uniprotkb:P53671 uniprotkb:P53608 uniprotkb:Q79VI7 uniprotkb:P0A4U6 }
    ?cluster up:member/up:sequenceFor ?protein;
             up:identity 0.5 .
    BIND(substr(str(?protein), strlen(str(uniprotkb:))+1) AS ?primaryAccession)
    BIND(substr(str(?cluster), strlen(str(uniref:))+1) AS ?cluster_id)
}

2it [00:03,  1.48s/it]

PREFIX up: <http://purl.uniprot.org/core/>
PREFIX uniprotkb: <http://purl.uniprot.org/uniprot/>
PREFIX uniref: <http://purl.uniprot.org/uniref/>

SELECT ?primaryAccession ?cluster_id
FROM <http://sparql.uniprot.org/uniref>
FROM <http://sparql.uniprot.org/uniprot>
WHERE
{
    VALUES ?protein { uniprotkb:Q54113 uniprotkb:P42676 uniprotkb:A4INJ9 uniprotkb:Q81VW8 uniprotkb:P03366 uniprotkb:Q90EA1 uniprotkb:P0C6F2 uniprotkb:P12499 uniprotkb:Q5ZZB6 uniprotkb:Q96PN6 uniprotkb:P42738 uniprotkb:Q8DRB3 uniprotkb:P00720 uniprotkb:P05121 uniprotkb:P08179 uniprotkb:P0AD64 uniprotkb:P43246 uniprotkb:E8ME30 uniprotkb:Q2HRB6 uniprotkb:P88911 uniprotkb:P29957 uniprotkb:P56634 uniprotkb:Q8U0A9 uniprotkb:P0C7B7 uniprotkb:P16154 uniprotkb:C3SQJ7 uniprotkb:A5F1K1 uniprotkb:P9WJJ7 uniprotkb:P02638 uniprotkb:P30694 uniprotkb:P56529 uniprotkb:P62942 uniprotkb:P22141 uniprotkb:P22756 uniprotkb:E0SJQ4 uniprotkb:P51668 uniprotkb:P00514 uniprotkb:Q9KL03 uniprotkb:Q13164 uniprotkb:O43148 uniprotkb:B1BQ33 uniprotkb:P51449 uniprotkb:P07379 uniprotkb:O31611 uniprotkb:O75874 uniprotkb:Q756Z6 uniprotkb:P11021 uniprotkb:P03147 uniprotkb:Q9WYL6 uniprotkb:P21728 uniprotkb:P29597 uniprotkb:O00763 uniprotkb:Q6VE93 uniprotkb:Q8WTX7 uniprotkb:Q09472 uniprotkb:O43526 uniprotkb:O75311 uniprotkb:P56373 uniprotkb:Q8I5R7 uniprotkb:Q9Y5K2 uniprotkb:P9WI55 uniprotkb:Q9H4A3 uniprotkb:Q96LA8 uniprotkb:Q8N6T7 uniprotkb:P31153 uniprotkb:P9WQN9 uniprotkb:P16790 uniprotkb:O75530 uniprotkb:Q99538 uniprotkb:O75643 uniprotkb:Q8I302 uniprotkb:Q8DW05 uniprotkb:P11881 uniprotkb:A0A0S4VB05 uniprotkb:O40922 uniprotkb:O60674 uniprotkb:P09237 uniprotkb:Q2N0S5 uniprotkb:P9WFX9 uniprotkb:A8EVM5 uniprotkb:A0A0X1KGP2 uniprotkb:Q8I719 uniprotkb:A0A1I9GEN8 uniprotkb:P0A183 uniprotkb:Q96T88 uniprotkb:Q460N5 uniprotkb:P23471 uniprotkb:P07949 uniprotkb:P36888 uniprotkb:P69681 uniprotkb:Q5SHU3 uniprotkb:P13491 uniprotkb:P66937 uniprotkb:Q9NPD8 uniprotkb:Q9BE39 uniprotkb:Q7DHH4 uniprotkb:Q8U093 uniprotkb:Q9CQV8 uniprotkb:P50213 uniprotkb:Q6YMS4 uniprotkb:A0A097PIE2 uniprotkb:P0DMV8 uniprotkb:Q4QDU3 uniprotkb:Q9H2S1 uniprotkb:A0A0H3JPA5 uniprotkb:P10587 uniprotkb:P39765 uniprotkb:O60547 uniprotkb:P04062 uniprotkb:P51686 uniprotkb:Q64610 uniprotkb:Q84HF5 uniprotkb:O75164 uniprotkb:P0A6V1 uniprotkb:P9WKE5 uniprotkb:O97193 uniprotkb:P60753 uniprotkb:P51553 uniprotkb:H7C677 uniprotkb:O15804 uniprotkb:P50620 uniprotkb:A3XHF9 uniprotkb:G4V8J4 uniprotkb:P55899 uniprotkb:Q4D9Z4 uniprotkb:E0TW95 uniprotkb:P54829 uniprotkb:P54830 uniprotkb:G7JFL4 uniprotkb:Q5HSJ4 uniprotkb:F2WR39 uniprotkb:L8A208 uniprotkb:A0A0J9X1X5 uniprotkb:F8RC03 uniprotkb:Q9I000 uniprotkb:Q8NNL5 uniprotkb:A9S498 uniprotkb:H6WFU3 uniprotkb:Q9HWY4 uniprotkb:F2WR52 uniprotkb:P54578 uniprotkb:Q9I4I1 uniprotkb:Q7KQK0 uniprotkb:A0A097J792 uniprotkb:A0A0E8T757 uniprotkb:D5KM69 uniprotkb:O35433 uniprotkb:O43353 uniprotkb:O93430 uniprotkb:P01111 uniprotkb:P11216 uniprotkb:P36022 uniprotkb:Q05785 uniprotkb:Q13976 uniprotkb:Q3AF10 uniprotkb:Q8NI77 uniprotkb:Q9R186 uniprotkb:A0A1L8F5J9 uniprotkb:Q60710 uniprotkb:G1M6C4 uniprotkb:P62330 uniprotkb:O00482 uniprotkb:P26045 uniprotkb:Q9UBL3 uniprotkb:A0A130G9H0 uniprotkb:P0A9G4 uniprotkb:Q9BJF5 uniprotkb:A0A059VAZ3 uniprotkb:Q8LPB4 uniprotkb:O43157 uniprotkb:P0AEY0 uniprotkb:P52917 uniprotkb:Q8TF76 uniprotkb:P22498 uniprotkb:O75317 uniprotkb:P78527 uniprotkb:V5HCK7 uniprotkb:P21243 uniprotkb:P18654 uniprotkb:Q9NY59 uniprotkb:V5TDZ4 uniprotkb:P09874 uniprotkb:P16471 uniprotkb:B0SN40 uniprotkb:Q9HV27 uniprotkb:Q9HVB9 uniprotkb:P21860 uniprotkb:A0A146CJG7 uniprotkb:Q5F4T5 uniprotkb:Q6V1X1 uniprotkb:O14744 uniprotkb:Q9I6J0 uniprotkb:Q9HXY6 uniprotkb:P10828 uniprotkb:Q8NBP7 uniprotkb:Q1DB04 uniprotkb:P0DTD1 uniprotkb:O15357 uniprotkb:P51570 uniprotkb:A0QWT2 }
    ?cluster up:member/up:sequenceFor ?protein;
             up:identity 0.5 .
    BIND(substr(str(?protein), strlen(str(uniprotkb:))+1) AS ?primaryAccession)
    BIND(substr(str(?cluster), strlen(str(uniref:))+1) AS ?cluster_id)
}

3it [00:04,  1.63s/it]

PREFIX up: <http://purl.uniprot.org/core/>
PREFIX uniprotkb: <http://purl.uniprot.org/uniprot/>
PREFIX uniref: <http://purl.uniprot.org/uniref/>

SELECT ?primaryAccession ?cluster_id
FROM <http://sparql.uniprot.org/uniref>
FROM <http://sparql.uniprot.org/uniprot>
WHERE
{
    VALUES ?protein { uniprotkb:Q9H7B4 uniprotkb:Q16F38 uniprotkb:Q15562 uniprotkb:Q4DJ68 uniprotkb:P49366 uniprotkb:A2A259 uniprotkb:P13995 uniprotkb:P17858 uniprotkb:Q6IDD9 uniprotkb:A0A144A134 uniprotkb:Q8S0S6 uniprotkb:A0A0G3E2X5 uniprotkb:Q4QCD2 uniprotkb:Q9Y2T5 uniprotkb:Q6NAM1 uniprotkb:P01011 uniprotkb:P38110 uniprotkb:P53762 uniprotkb:Q6SZW1 uniprotkb:P04908 uniprotkb:Q96RR4 uniprotkb:P11388 uniprotkb:A0A0U3FQH7 uniprotkb:O00167 uniprotkb:Q91H74 uniprotkb:Q9Y6W6 uniprotkb:P30559 uniprotkb:Q9LZX6 uniprotkb:Q1XA76 uniprotkb:V5VHN7 uniprotkb:P0A2C9 uniprotkb:P30793 uniprotkb:P47870 uniprotkb:Q9I188 uniprotkb:P9WN93 uniprotkb:P99165 uniprotkb:Q9NQR1 uniprotkb:Q6MZV7 uniprotkb:Q9UBE0 uniprotkb:B9ZW32 uniprotkb:P14488 uniprotkb:P51531 uniprotkb:Q8NP91 uniprotkb:P0ADR8 uniprotkb:P74881 uniprotkb:A6TFK2 uniprotkb:Q43837 uniprotkb:O95256 uniprotkb:Q01IX6 uniprotkb:A0A024B7W1 uniprotkb:Q9P2K8 uniprotkb:P00183 uniprotkb:Q9UBK2 uniprotkb:P9WK11 uniprotkb:Q19905 uniprotkb:P50120 uniprotkb:Q9S5X0 uniprotkb:Q9HWK2 uniprotkb:P62575 uniprotkb:Q4FTX3 uniprotkb:F0NE21 uniprotkb:P50098 uniprotkb:P0AES6 uniprotkb:Q5SHL3 uniprotkb:P9WN94 uniprotkb:P0AFA1 uniprotkb:O43739 uniprotkb:A6V1E4 uniprotkb:A0A098D3M4 uniprotkb:V4JF97 uniprotkb:A0A0U1RGY0 uniprotkb:P0AEW6 uniprotkb:Q8Y8A3 uniprotkb:P0A031 uniprotkb:O14733 uniprotkb:Q92542 uniprotkb:Q9VUL1 uniprotkb:A0A0F4VK59 uniprotkb:Q81P63 uniprotkb:Q5ZSB6 uniprotkb:Q9WUD2 uniprotkb:P51684 uniprotkb:P47811 uniprotkb:B0SUI1 uniprotkb:O00411 uniprotkb:P01031 uniprotkb:Q8TB36 uniprotkb:Q8TDU6 uniprotkb:Q9Y5P6 uniprotkb:P58743 uniprotkb:A0A140NBS6 uniprotkb:A0A3Q0KFL1 uniprotkb:P09958 uniprotkb:P97481 uniprotkb:Q54324 uniprotkb:A0A0A7HIX1 uniprotkb:Q9I834 uniprotkb:P0A0K8 uniprotkb:P00338 uniprotkb:O15648 uniprotkb:nan }
    ?cluster up:member/up:sequenceFor ?protein;
             up:identity 0.5 .
    BIND(substr(str(?protein), strlen(str(uniprotkb:))+1) AS ?primaryAccession)
    BIND(substr(str(?cluster), strlen(str(uniref:))+1) AS ?cluster_id)
}

4it [00:06,  1.54s/it]

In [13]:
df_asd_merged[df_asd_merged['uniref50_cluster'].isna()]

,target_id,target_gene,organism,pdb_uniprot,allosteric_pdb,modulator_serial,modulator_alias,modulator_chain,modulator_class,modulator_feature,...,modulator_resi,function,position,pubmed_id,ref_title,site_overlap,allosteric_site_residue,allosteric_site_chains,uniprot_id,uniref50_cluster
94,ASD00330000_2,pyrB,E.coli,E8Y329,4KH0,ASD00330030;ASD01140145;ASD00330030,ATP;MG;ATP,B;B;B,Lig,Activator,...,202;203;204,Inner Protein Regulator,Inner Protein,24138583,New Paradigm for Allosteric Regulation of Esch...,No,"['B-ALA-11', 'B-ILE-12', 'B-VAL-17', 'B-ASP-19...","{B, D}",NaN,NaN
95,ASD00330000_2,pyrB,E.coli,E8Y329,4KH1,ASD00150003;ASD00150002;ASD00330030,CTP;MG;UTP,B;B;B,Lig,Inhibitor,...,202;203;204,Inner Protein Regulator,Inner Protein,24138583,New Paradigm for Allosteric Regulation of Esch...,No,"['B-LEU-7', 'B-GLN-8', 'B-VAL-9', 'B-ALA-11', ...",{B},NaN,NaN
96,ASD00330000_2,pyrB,E.coli,E8Y329,4KGX,ASD00150003,CTP,B,Lig,Inhibitor,...,202,Inner Protein Regulator,Inner Protein,24138583,New Paradigm for Allosteric Regulation of Esch...,No,"['B-GLU-10', 'B-ALA-11', 'B-ILE-12', 'B-VAL-17...",{B},NaN,NaN
97,ASD00330000_2,pyrB,E.coli,E8Y329,4KGV,ASD00150001,ATP,B,Lig,Activator,...,202,Inner Protein Regulator,Inner Protein,24138583,New Paradigm for Allosteric Regulation of Esch...,No,"['B-ALA-11', 'B-ILE-12', 'B-VAL-17', 'B-ASP-19...",{B},NaN,NaN
164,ASD00470000_3,CALM1,Human,P62158,1NWD,ASD11630001;ASD11630001;ASD11630001;ASD11630001,CA;CA;CA;CA,A;A;A;A,Ion,Regulator,...,149;150;151;152,Inner Protein Regulator,Inner Protein,12684008,Structural Basis for Simultaneous Binding of T...,No,"['A-LYS-94', 'A-MET-71', 'A-ASP-95', 'A-PHE-92...",{A},NaN,NaN
165,ASD00470000_3,CALM1,Human,P62158,1IQ5,ASD11630001;ASD11630001;ASD11630001;ASD11630001,CA;CA;CA;CA,A;A;A;A,Ion,Regulator,...,361;362;363;364,Inner Protein Regulator,Inner Protein,11545585,Target-induced conformational adaptation of ca...,No,"['A-LYS-94', 'A-ASP-95', 'A-PHE-92', 'A-GLY-96...",{A},NaN,NaN
166,ASD00470000_3,CALM1,Human,P62158,3J41,ASD11630001;ASD11630001;ASD11630001;ASD11630001,CA;CA;CA;CA,E;E;E;E,Ion,Regulator,...,201;202;203;204,Inner Protein Regulator,Inner Protein,23893133,Allosteric mechanism of water-channel gating b...,No,"['E-GLY-134', 'E-TYR-99', 'E-LYS-94', 'E-ASP-9...",{E},NaN,NaN
167,ASD00470000_3,CALM1,Human,P62158,1CKK,ASD11630001;ASD11630001;ASD11630001;ASD11630001,CA;CA;CA;CA,A;A;A;A,Ion,Regulator,...,151;152;153;154,Inner Protein Regulator,Inner Protein,10467092,A novel target recognition revealed by calmodu...,No,"['A-LYS-94', 'A-GLU-54', 'A-ASP-95', 'A-PHE-92...",{A},NaN,NaN
206,ASD00480000_2,crp,Mycobacterium tuberculosis,I6Y496,4A2U,ASD00480003,CMP,A,Lig,Activator,...,280,Protein-DNA/RNA Interaction Regulator,Protein-Protein Interaction,NaN,A New Crystal Form of Crp from M. Tuberculosis...,No,"['A-PHE-38', 'A-ILE-57', 'A-LEU-69', 'A-THR-70...","{B, A}",NaN,NaN
744,ASD01510000_3,HSPA1A,Human,P08107,4IO8,ASD01510007,3FD,A,Lig,Inhibitor,...,401,Protein-Protein Interaction Regulator,Inner Protein,24265689,Functional analysis of hsp70 inhibitors.,No,"['A-TYR-15', 'A-ASN-35', 'A-THR-37', 'A-GLY-20...",{A},NaN,NaN
1156,ASD02980000_2,NaN,Bacillus anthracis,Q81K32,3BEO,ASD10298001,UD1,A,Lig,Activator,...,372,Inner Protein Regulator,Inner Protein,18188181,A structural basis for the allosteric regulati...,Yes,"['A-PRO-15', 'A-GLN-43', 'A-HIS-44', 'A-ARG-45...",{A},NaN,NaN
1159,ASD02990000_1,pyrH1,Bacillus anthracis,Q81S73,2JJX,ASD00150001,ATP,A,Lig,Regulator,...,1246,Inner Protein Regulator,Protein-Protein Interaction,18625239,The Crystal Structure of Ump Kinase from Bacil...,No,"['B-HIS-120', 'B-ILE-114', 'B-ARG-117', 'B-ASN...",{B},NaN,NaN
1767,ASD05550000_3,pycA,Staphylococcus aureus,Q99UY8,3HO8,ASD05550003,COA,A,Lig,Activator,...,2001,Inner Protein Regulator,Protein-Protein Interaction,19523900,A Symmetrical Tetramer for S. aureus Pyruvate ...,No,"['A-ARG-398', 'A-ARG-448', 'A-GLU-449', 'A-ARG...","{C, A}",NaN,NaN
1768,ASD05550000_5,pycA,Listeria monocytogenes R479a,L8DYY9,4QSK,ASD05550002,2BA,A,Lig,Regulator,...,2000,Inner Protein Regulator,Inner Protein,25215494,The Cyclic Dinucleotide c-di-AMP Is an Alloste...,No,"['A-TYR-722', 'A-TYR-749', 'A-LEU-785', 'A-GLN...",{A},NaN,NaN
1769,ASD05550000_5,pycA,Listeria monocytogenes R479a,L8DYY9,4QSH,ASD05550002,2BA,A,Lig,Regulator,...,2004,Inner Protein Regulator,Inner Protein,25215494,The Cyclic Dinucleotide c-di-AMP Is an Alloste...,No,['D-SER-756'],{D},NaN,NaN
1818,ASD06120000_2,ugd,Klebsiella pneumoniae,C4XAX5,3PJG,ASD06120002,UGA,A,Lig,Inhibitor,...,902,Inner Protein Regulator,Inner Protein,21536136,Conformational change upon product binding to ...,No,"['A-LYS-256', 'A-ASP-257', 'A-LYS-259', 'A-LYS...",{A},NaN,NaN
1960,ASD07970000_1,glc-1,Caenorhabditis elegans,O17793,3RIF,ASD07970001,IVM,A,Lig,Activator,...,402,Inner Protein Regulator,Protein-Protein Interaction,21572436,Principles of activation and permeation in an ...,No,"['A-THR-257', 'A-SER-260', 'A-ASN-264', 'A-ILE...","{B, A}",NaN,NaN
1961,ASD07970000_1,glc-1,Caenorhabditis elegans,O17793,3RI5,ASD07970001,IVM,B,Lig,Activator,...,349,Inner Protein Regulator,Protein-Protein Interaction,21572436,Principles of activation and permeation in an ...,No,"['A-THR-257', 'A-SER-260', 'A-ASN-264', 'A-ILE...","{B, A}",NaN,NaN
1962,ASD07970000_1,glc-1,Caenorhabditis elegans,O17793,3RHW,ASD07970001,IVM,B,Lig,Activator,...,348,Inner Protein Regulator,Protein-Protein Interaction,21572436,Principles of activation and permeation in an ...,No,"['A-THR-257', 'A-SER-260', 'A-ILE-273', 'A-ASP...","{B, A}",NaN,NaN
1963,ASD07970000_1,glc-1,Caenorhabditis elegans,O17793,3RIA,ASD07970001,IVM,A,Lig,Activator,...,348,Inner Protein Regulator,Protein-Protein Interaction,21572436,Principles of activation and permeation in an ...,No,"['A-THR-257', 'A-SER-260', 'A-ILE-273', 'A-ASP...","{B, A}",NaN,NaN
2132,ASD09460000_1,pelD,Pseudomonas aeruginosa,Q02PM6,4DN0,ASD06980001;ASD06980001,C2E;C2E,A;A,Lig,Inhibitor,...,501;502,Inner Protein Regulator,Inner Protein,22605337,"Structure of the Cytoplasmic Region of PelD, a...",No,"['A-ARG-161', 'A-LEU-165', 'A-GLN-366', 'A-ARG...",{A},NaN,NaN
2226,ASD10100000_4,NaN,Salmonella paratyphi B,A9N7P9,1MP3,ASD02040015,TTP,A,Lig,Inhibitor,...,504,Inner Protein Regulator,Protein-Protein Interaction,12374866,Expanding pyrimidine diphosphosugar libraries ...,No,"['A-LEU-46', 'A-TYR-115', 'A-GLY-116', 'A-HIS-...","{B, A}",NaN,NaN
2431,ASD11870000_1,mecA,Staphylococcus aureus,Q54113,3ZG0,ASD11870001,MUR,A,Lig,Activator,...,1677,Inner Protein Regulator,Inner Protein,24085846,How Allosteric Control of Staphylococcus Aureu...,No,"['A-THR-165', 'A-GLU-239', 'A-VAL-256', 'A-ILE...",{A},NaN,NaN
2432,ASD11870000_1,mecA,Staphylococcus aureus,Q54113,3ZFZ,ASD11870001,MUR,A,Lig,Activator,...,1670,Inner Protein Regulator,Inner Protein,24085846,How Allosteric Control of Staphylococcus Aureu...,No,"['A-THR-165', 'A-GLU-239', 'A-VAL-256', 'A-GLY...",{A},NaN,NaN
2433,ASD11870000_1,mecA,Staphylococcus aureus,Q54113,3ZFZ,ASD11870002,1W8,A,Lig,Activator,...,1669,Inner Protein Regulator,Protein-Protein Interaction,24085846,How Allosteric Control of Staphylococcus Aureu...,No,"['B-ILE-309', 'B-ASN-305', 'B-LEU-147', 'B-ASN...",{B},NaN,NaN
2434,ASD11870000_1,mecA,Staphylococcus aureus,Q54113,3ZG0,ASD11870002,1W8,A,Lig,Activator,...,1676,Inner Protein Regulator,Protein-Protein Interaction,24085846,How Allosteric Control of Staphylococcus Aureu...,No,"['B-ILE-309', 'B-LEU-147', 'B-THR-308', 'B-ASN...",{B},NaN,NaN
2571,ASD12220000_1,NaN,Vibrio cholerae serotype O1,A5F1K1,2RDE,ASD06980001,C2E,A,Lig,Activator,...,301,Protein-Protein Interaction Regulator,Inner Protein,18034161,The structural basis of cyclic diguanylate sig...,No,"['A-ILE-96', 'A-LEU-135', 'A-ARG-136', 'A-LYS-...",{A},NaN,NaN
2867,ASD16720000_1,NaN,Blood fluke,G4V8J4,6FMZ,ASD16720002,DVQ,A,Lig,Inhibitor,...,601,Allosteric function,Allosteric position,29800515,Fragment-Based Discovery of a Regulatory Site ...,No,"['A-ILE-431', 'A-LEU-120', 'A-LYS-399', 'A-LEU...",{A},NaN,NaN
2868,ASD16720000_1,NaN,Blood fluke,G4V8J4,6FMU,ASD16720001,DVK,A,Lig,Inhibitor,...,602,Allosteric function,Allosteric position,29800515,Fragment-Based Discovery of a Regulatory Site ...,No,"['A-ASP-325', 'A-VAL-469', 'A-LEU-537', 'A-ALA...",{A},NaN,NaN
2869,ASD16720000_1,NaN,Blood fluke,G4V8J4,6FTC,ASD03080094,EPE,A,Lig,Inhibitor,...,602,Allosteric function,Allosteric position,29800515,Fragment-Based Discovery of a Regulatory Site ...,No,"['A-ASP-325', 'A-VAL-469', 'A-LEU-537', 'A-ALA...",{A},NaN,NaN
2870,ASD16720000_1,NaN,Blood fluke,G4V8J4,6FP4,ASD16720003,E1T,A,Lig,Inhibitor,...,604,Allosteric function,Allosteric position,29800515,Fragment-Based Discovery of a Regulatory Site ...,No,"['A-GLU-300', 'A-LEU-321', 'A-THR-472', 'A-LYS...",{A},NaN,NaN
2936,ASD17210000_1,tdcG,Legionella pneumophila,A0A130G9H0,4RQO,NaN,Cys,NaN,Lig,Inhibitor,...,458,Allosteric Function,Allosteric Position,NaN,NaN,Yes,[],{},NaN,NaN
3014,ASD18980000_1,speG,Bacillus thuringiensis,A0A0G3E2X5,6VFN,NaN,SPM,A,Lig,NaN,...,201,NaN,NaN,NaN,NaN,NaN,[],{},NaN,NaN
3158,ASD80060000_2,gcvT,Vibrio cholerae,NaN,3OWZ,ASD01260003,GLY,A,Lig,Regulator,...,89,Inner DNA/RNA Regulator,Inner DNA/RNA,21145485,Structural insights into ligand recognition by...,No,['A-GLY-36'],{A},NaN,NaN
3159,ASD80060000_2,gcvT,Vibrio cholerae,NaN,3OXM,ASD01260003,GLY,A,Lig,Regulator,...,89,Inner DNA/RNA Regulator,Inner DNA/RNA,21145485,Structural insights into ligand recognition by...,No,['A-GLY-36'],{A},NaN,NaN
3160,ASD80060000_2,gcvT,Vibrio cholerae,NaN,3MUT,ASD06980001,C2E,R,Lig,Regulator,...,1,Protein-DNA/RNA Interaction Regulator,Inner DNA/RNA,20690679,Structural and biochemical determinants of lig...,No,['R-ALA-47'],{R},NaN,NaN
3161,ASD80060000_2,gcvT,Vibrio cholerae,NaN,3OWI,ASD01260003,GLY,A,Lig,Regulator,...,89,Inner DNA/RNA Regulator,Inner DNA/RNA,21145485,Structural insights into ligand recognition by...,No,['A-GLY-36'],{A},NaN,NaN
3162,ASD80060000_2,gcvT,Vibrio cholerae,NaN,3MUR,ASD06980001,C2E,R,Lig,Regulator,...,1,Protein-DNA/RNA Interaction Regulator,Inner DNA/RNA,20690679,Structural and biochemical determinants of lig...,No,['R-ALA-47'],{R},NaN,NaN
3163,ASD80060000_2,gcvT,Vibrio cholerae,NaN,3Q3Z,ASD06980001,C2E,A,Lig,Regulator,...,2,Protein-DNA/RNA Interaction Regulator,Inner DNA/RNA,21518891,Structural basis of differential ligand recogn...,No,['A-ALA-70'],{A},NaN,NaN
3164,ASD80060000_2,gcvT,Vibrio cholerae,NaN,3IWN,ASD06980001,C2E,A,Lig,Regulator,...,501,Protein-DNA/RNA Interaction Regulator,Inner DNA/RNA,19898478,Recognition of the bacterial second messenger ...,No,['A-CYS-88'],{A},NaN,NaN
3165,ASD80060000_2,gcvT,Vibrio cholerae,NaN,3MUV,ASD05550002,2BA,R,Lig,Regulator,...,358,Protein-DNA/RNA Interaction Regulator,Inner DNA/RNA,20690679,Structural and biochemical determinants of lig...,No,['R-ALA-47'],{R},NaN,NaN
3166,ASD80060000_2,gcvT,Vibrio cholerae,NaN,3OXJ,ASD01260003,GLY,A,Lig,Regulator,...,89,Inner DNA/RNA Regulator,Inner DNA/RNA,21145485,Structural insights into ligand recognition by...,No,['A-GLY-36'],{A},NaN,NaN
3167,ASD80060000_2,gcvT,Vibrio cholerae,NaN,3OWW,ASD01260003,GLY,A,Lig,Regulator,...,89,Inner DNA/RNA Regulator,Inner DNA/RNA,21145485,Structural insights into ligand recognition by...,No,['A-GLY-36'],{A},NaN,NaN
3168,ASD80060000_2,gcvT,Vibrio cholerae,NaN,3IRW,ASD06980001,C2E,R,Lig,Regulator,...,1,Protein-DNA/RNA Interaction Regulator,Inner DNA/RNA,19898477,Structural basis of ligand binding by a c-di-G...,No,['R-ALA-47'],{R},NaN,NaN
3169,ASD80060000_2,gcvT,Vibrio cholerae,NaN,3MXH,ASD06980001,C2E,R,Lig,Regulator,...,1,Protein-DNA/RNA Interaction Regulator,Inner DNA/RNA,20690679,Structural and biochemical determinants of lig...,No,['R-ALA-47'],{R},NaN,NaN
3170,ASD80060000_2,gcvT,Vibrio cholerae,NaN,3OXE,ASD01260003,GLY,A,Lig,Regulator,...,89,Inner DNA/RNA Regulator,Inner DNA/RNA,21145485,Structural insights into ligand recognition by...,No,['A-GLY-36'],{A},NaN,NaN
3171,ASD80060000_2,gcvT,Vibrio cholerae,NaN,3MUM,ASD06980001,C2E,R,Lig,Regulator,...,1,Protein-DNA/RNA Interaction Regulator,Inner DNA/RNA,20690679,Structural and biochemical determinants of lig...,No,['R-ALA-47'],{R},NaN,NaN

In [11]:
df_unselected = df_merged[df_merged['uniref_cluster'].isin(training_clusters)]

print('Number of Rows:             ', df_unselected.shape[0])
print('Number of Unique PDB IDs:   ', df_unselected['allosteric_pdb'].nunique())
print('Number of Unique UniProt AC:', df_unselected['pdb_uniprot'].nunique())

NameError: name 'df_merged' is not defined

In [ ]:
df_selected = df_merged[~df_merged['uniref_cluster'].isin(training_clusters)]

print('Number of Rows:             ', df_selected.shape[0])
print('Number of Unique PDB IDs:   ', df_selected['allosteric_pdb'].nunique())
print('Number of Unique UniProt AC:', df_selected['pdb_uniprot'].nunique())

## Download PDB files

In [ ]:
if not os.path.exists('data/pdb_downloaded/'):
    os.makedirs('data/pdb_downloaded/')

for pdb_id in tqdm(list(set(df_selected['allosteric_pdb']))):
    if not os.path.exists(f'data/pdb_downloaded/{pdb_id}.pdb'):
        try:
            urllib.request.urlretrieve(f'https://files.rcsb.org/download/{pdb_id.lower()}.pdb1', f'data/pdb_downloaded/{pdb_id}.pdb')
        except:
            print(pdb_id)

PDB ID 4V9C does not have a .pdb format file available.

In [ ]:
residues = []
for pdb_file in tqdm(glob('data/pdb_downloaded/*.pdb')):
    pdb_id = os.path.splitext(os.path.basename(pdb_file))[0]
    
    parser = PDBParser()
    with warnings.catch_warnings(action="ignore"):
        structure = parser.get_structure(pdb_id, pdb_file)

    for residue in structure.get_residues():
        structure, model, chain, (hetfield, res_id, _) = residue.get_full_id()
        res_name = residue.get_resname()
        if hetfield == ' ':
            residues.append([structure, model, chain, res_id, res_name])
    
df_residues = pd.DataFrame(residues, columns=['structure', 'model', 'chain', 'res_id', 'res_name'])

In [ ]:
df_sub = df_selected[['allosteric_pdb', 'Sequence', 'Active_or_Binding_Site']].drop_duplicates()

df_sub = df_sub.drop(df_selected[(df_selected['allosteric_pdb'] == '4V9C')].index)

df_sub['Active_or_Binding_Site'] = df_sub['Active_or_Binding_Site'].apply(eval)
df_sub = df_sub.explode('Active_or_Binding_Site')

df_sub['res_name'] = df_sub.apply(lambda x: protein_letters_1to3[x['Sequence'][x['Active_or_Binding_Site'] - 1]], axis=1)

df_sub['res_id'] = df_sub['Active_or_Binding_Site'].astype("Int64")
df_sub.drop(columns=['Sequence', 'Active_or_Binding_Site'], inplace=True)
df_sub.rename(columns={'allosteric_pdb': 'structure'}, inplace=True)

In [ ]:
df_merge = df_sub.merge(df_residues, how='left', on=['structure', 'res_id', 'res_name'], indicator=True).drop_duplicates()
mismatch_structures = df_merge.loc[df_merge['_merge'] == 'left_only', 'structure'].unique()
len(mismatch_structures)

In [ ]:
df_merge_match = df_merge[~df_merge['structure'].isin(mismatch_structures)].copy()

df_merge_match['active_site'] = df_merge_match['chain'] + '-' + df_merge_match['res_id'].astype(str) + '-' + df_merge_match['res_name']
df_grouped = df_merge_match[['structure', 'active_site']].groupby(['structure']).agg(set).reset_index()

In [ ]:
df_selected_no_mismatch = df_selected.merge(df_grouped, left_on='allosteric_pdb', right_on='structure')

In [ ]:
print('Number of Rows:             ', df_selected_no_mismatch.shape[0])
print('Number of Unique PDB IDs:   ', df_selected_no_mismatch['allosteric_pdb'].nunique())
print('Number of Unique UniProt AC:', df_selected_no_mismatch['pdb_uniprot'].nunique())

In [ ]:
df_selected_no_mismatch[[
    'target_id', 'target_gene', 'organism', 'pdb_uniprot', 'allosteric_pdb',
    'modulator_serial', 'modulator_alias', 'modulator_chain',
    'modulator_class', 'modulator_feature', 'modulator_name',
    'modulator_resi', 'function', 'position', 'pubmed_id', 'ref_title',
    'site_overlap', 'allosteric_site_residue', 'active_site']].to_csv('test_set.csv', index=False)